[package]

name = "mudpie"
version = "0.2.6"
authors = ["kjp"]
description = "Dynamic HTTP Server.  Pure safe Rust, no dependencies."
repository = "https://github.com/kjpgit/mudpie"
readme = "README.adoc"
license = "Unlicense"
